### ISSUE TITLE
Investigate and Decipher Data Format

### ISSUE THREAD

**Issue by ghost** [GTBitsOfGood/gt-scheduler#1]
## Problem Description
Considering the extent to which we'll be working with Jason Park's web scraper, it makes sense to first understand the data provided before contributing to the application. Correspondingly, I recommend you `curl` the scraper's URL and use a JSON manipulation tool (e.g. `jq`, `fx`, etc) to parse and format the data.

For instance, try running `curl -s https://jasonpark.me/gt-schedule-crawler/202008.json | jq '.courses["CS 7650"]'`. The outputted array (shown below) contains information about the class name, its corresponding sections, professors, schedules, CRNs, etc. Much of the information is obvious at first glance; however, the output also contains somewhat cryptic information, such as the string of seemingly random numbers near the end of a class object.

## Your Goal
- Figure out what each component of the output is representative of.
- Develop up a generalized outline of the data where each value is decoded (e.g. "91428" → \<String\> CRN).
- Send @nichabosh your findings or leave it as a comment under this issue. 🎉

<br /><img width="1000" alt="output" src="https://bit.ly/3klrSfD">

**Comment by JHDeerin** [comment]
# Data Format Findings

As of September 16th, 2020, the raw JSON object returned by Jason Park's API has 3 main attributes:

-   `courses`, which contains information about each class (see below for details); this makes up the vast bulk of the JSON file
-   `caches`, which contains the following data shared by multiple class descriptions; **all of the data is stored in a string format**:
    -   `periods` has a list of all the different time ranges that classes can be offered at (e.g. "8:00 am - 8:50 am"; there is one "TBA" string for classes whose time is "To Be Announced")
    -   `dateRanges` has a list of all possible start/ending dates that classes can be offered between (e.g. "Aug 17, 2020 - Dec 10, 2020")
    -   `scheduleTypes` has a list of the different types of classes for each time block (e.g. "Lecture*", "Recitation*", or "Internship/Practicum*")
        -   TODO: Research what all of these mean, if needed?
    -   `campuses` has a list of the different GT campus locations that a class could take place at (e.g. "Georgia Tech-Atlanta *" or "Online")
    -   `attributes` has a list of other miscellaneous attributes that can be associated with a class (e.g. "Hybrid Course", "Honors Program", or "Capstone")
        -   TODO: Research what all of these mean, if needed?
    -   `gradeBases` has a list of the different kinds of grading schemes a course can have
        -   TODO: Research what all of these mean, if needed?
-   `updatedAt`, which contains the time this JSON file was retrieved as an ISO string

Currently, the entire JSON file containing all classes is ~1 MB in size, being over 250,000 lines long. After being retrieved from the API, this data is processed in the `src/beans/Oscar.js` file so that it's usable by the rest of the application.

## Course Item Format

`courses` itself is a JSON object with the abbreviated course ID name of each class as the key (e.g. "ACCT 2101", "PHIL 3050", "CS 1332"). Once accessed, each course is an **array** containing the following 2 items:

-   `[0]` contains the full, human-readable name of the course (e.g. "Accounting I")
-   `[1]` contains a JSON object with information about each section of the course; the section IDs are the keys ("A", "B", "S2", etc.), and the value is an array

### Section information

Each section contains the same type of information about the course's section, stored in an array:

-   `[0]` contains the CRN number of this section of the course
-   `[1]` contains an array of information about the section's meeting times/places/professors/etc.; in most cases, this array will only contain 1 item
    -   `[0]`, which is *another* array nested inside containing the meeting information. *This* internal array has the following information:
        -   `[0]` is an integer index into `caches.periods`, specifying the class's start/end times
        -   `[1]` is a string specifying what days the class takes place on (e.g. "MW" or "TR")
        -   `[2]` is a string giving the room/location where the course will be held (e.g. "College of Business 224")
        -   `[3]` is an array of strings listing all the instructors for this section, along with a 1-character code to mark the principal instructor (e.g. `["Katarzyna Rubar (P)"]`)
        -   `[4]` is an integer index into `caches.dateRanges`, specifying the start/end date of the class this semester
    -   In the rare case there's more than 1 item, they will be additional array items that follow the same format above
-   `[2]` is the integer number of credit hours this course is worth
-   `[3]` is an integer index into `caches.scheduleTypes`,
-   `[4]` is an integer index into `caches.campuses`, specifying which campus the class is being taught at
-   `[5]` is an array of integer indices into `caches.attributes`, specifying any additional attributes the course has
-   `[6]` is an integer index into `caches.gradeBases`, specifying the grading scheme of the class

## Example JSON Response

```json
{
  "courses": {
    "ACCT 2101": [      // Course ID string : array of info
      "Accounting I",   // Full course name
      {
        "D": [          // Section ID : array of info
          "86385",      // Section CRN (course registration #)
          [
            [
              2,        // caches.periods index, specifies meet time
              "TR",     // Days when this section meets
              "TBA",    // Location of this section
              [
                "Nicole Lena Mackenzie (P)",
                //  (...more instructors...)
              ],
              0         // caches.dateRanges index, specifies start/ending dates
            ]
          ],
          3,            // # of credit hours for course
          0,            // caches.scheduleTypes index, specifies type of class
          0,            // caches.campuses index, specifies campus of course
          [
            1,          // caches.attributes index
            // (...additional attribute indices...)
          ],
          0             // caches.gradeBases index, specifies grading scheme
        ],
        // (...more class sections...)
      }
    ],
    // (...more courses...)
  },
  "caches": {
    "periods": [
      "9:30 am - 10:45 am",
      // (...additional time periods...)
    ],
    "dateRanges": [
      "Aug 17, 2020 - Dec 10, 2020",
      // (...additional dates...)
    ],
    "scheduleTypes": [
      "Lecture*",
      // (...additional types...)
    ],
    "campuses": [
      "Georgia Tech-Atlanta *",
      // (...additional campuses...)
    ],
    "attributes": [
      "Hybrid Course",
      // (...additional attributes...)
    ],
    "gradeBases": [
      "ALP ",
      // (...additional grade bases...)
    ]
  },
  "updatedAt": "2020-09-17T01:11:11.426Z"   // Time this JSON file was retrieved
}
```

## Full Caches Lists (*as of 9/16/2020*)

```json
"caches": {
  "periods": [
    "9:30 am - 10:45 am",
    "11:00 am - 12:15 pm",
    "2:00 pm - 3:15 pm",
    "3:30 pm - 4:45 pm",
    "12:30 pm - 1:20 pm",
    "5:00 pm - 5:50 pm",
    "6:30 pm - 9:15 pm",
    "12:30 pm - 1:45 pm",
    "8:25 am - 10:20 am",
    "7:55 am - 9:30 am",
    "9:45 am - 10:50 am",
    "6:30 pm - 7:45 pm",
    "2:00 pm - 2:50 pm",
    "3:30 pm - 5:25 pm",
    "TBA",
    "9:30 am - 10:20 am",
    "11:00 am - 11:50 am",
    "12:30 pm - 2:25 pm",
    "6:30 pm - 8:25 pm",
    "8:25 am - 9:15 am",
    "3:30 pm - 6:15 pm",
    "3:30 pm - 4:20 pm",
    "2:00 pm - 4:45 pm",
    "3:00 pm - 4:30 pm",
    "1:45 pm - 3:15 pm",
    "5:00 pm - 6:15 pm",
    "12:30 pm - 3:15 pm",
    "4:15 pm - 5:30 pm",
    "1:30 pm - 3:00 pm",
    "6:30 am - 7:45 am",
    "8:00 am - 9:15 am",
    "12:30 pm - 4:20 pm",
    "8:00 am - 10:45 am",
    "6:30 pm - 7:20 pm",
    "11:00 am - 12:55 pm",
    "3:50 pm - 5:05 pm",
    "3:00 pm - 4:15 pm",
    "10:30 am - 12:00 pm",
    "5:00 pm - 7:45 pm",
    "2:00 pm - 3:55 pm",
    "12:30 pm - 6:15 pm",
    "6:05 pm - 8:50 pm",
    "9:00 am - 11:45 am",
    "12:45 pm - 5:00 pm",
    "5:00 pm - 6:55 pm",
    "11:00 am - 1:45 pm",
    "11:30 am - 4:00 pm",
    "1:30 pm - 3:05 pm",
    "3:15 pm - 4:50 pm",
    "9:00 am - 10:30 am",
    "10:45 am - 12:15 pm",
    "9:40 am - 11:15 am",
    "11:25 am - 12:30 pm",
    "9:35 am - 12:35 pm",
    "5:00 pm - 6:05 pm",
    "3:45 pm - 4:50 pm",
    "3:25 pm - 4:30 pm",
    "9:00 am - 10:35 am",
    "2:45 pm - 4:00 pm",
    "3:30 pm - 5:00 pm",
    "1:45 pm - 2:45 pm",
    "5:00 pm - 6:35 pm",
    "8:00 am - 11:50 am",
    "1:00 pm - 3:45 pm",
    "8:30 am - 4:40 pm",
    "8:15 am - 9:20 am",
    "11:20 am - 1:00 pm",
    "11:25 am - 1:00 pm",
    "4:30 pm - 6:15 pm",
    "1:30 pm - 2:50 pm",
    "6:30 am - 8:25 am",
    "8:30 am - 11:15 am",
    "6:30 am - 9:15 am",
    "2:25 pm - 3:15 pm",
    "5:45 am - 6:35 am",
    "7:00 pm - 9:00 pm",
    "4:35 pm - 5:25 pm",
    "1:35 pm - 2:25 pm",
    "8:00 pm - 8:50 pm"
  ],
  "dateRanges": [
    "Aug 17, 2020 - Dec 10, 2020",
    "Aug 17, 2020 - Oct 09, 2020",
    "Aug 17, 2020 - Sep 18, 2020",
    "Oct 26, 2020 - Dec 01, 2020",
    "Sep 21, 2020 - Oct 23, 2020",
    "Oct 12, 2020 - Dec 10, 2020"
  ],
  "scheduleTypes": [
    "Lecture*",
    "Supervised Laboratory*",
    "Recitation*",
    "Breakout*",
    "Directed Study*",
    "Studio*",
    "Thesis*",
    "Unsupervised Laboratory*",
    "Dissertation*",
    "Seminar*",
    "Internship/Practicum*",
    "Mixed Laboratory*",
    "Co-op Work Assignment",
    "Common Exam*",
    "Practice Teaching*"
  ],
  "campuses": [
    "Georgia Tech-Atlanta *",
    "GT Lorraine-Undergrad Programs",
    "Video",
    "GT Lorraine-Graduate Programs",
    "GT, Peking University, & Emory",
    "Georgia Tech Studies Abroad",
    "Online",
    "GT Lorraine",
    "Georgia Tech - Shenzhen",
    "GT-Lorraine",
    "MBA Evening Program",
    "Camden Resident Center*",
    "Georgia Tech - Shanghai",
    "Foreign Exchange",
    "Global",
    "Georgia Southern/GTREP",
    "Georgia Tech-Savannah",
    "Georgia Tech - Korea"
  ],
  "attributes": [
    "Hybrid Course",
    "Isolate Course in Canvas",
    "Remote Synchronous Course",
    "STEM USG",
    "GTL Metz (UG Program)",
    "One Semester",
    "Study Abroad",
    "Branch Campus Abroad",
    "Tech Elect CS",
    "Engr",
    "&Sciences",
    "Low-cost $40 or undr req txtbk",
    "Res/CP  >= 101 cont hrs",
    "Serve Learn Sustain",
    "Capstone",
    "No-cost $0 req'd textbooks",
    "Residential Course",
    "Military Science Course",
    "Remote Asynchronous Course",
    "Shenzhen Freshman Cohort",
    "Humanities Requirement",
    "Country and Region (IP)",
    "Ethics Requirement",
    "Barcelona Science Fall Program",
    "Faculty Let",
    "Social Science Requirement",
    "Honors Program",
    "OMSCS GT Lorraine",
    "Computer Systems (CS)",
    "Networking & Telecom (CS)",
    "Graphics & Visualization (CS)",
    "Intelligent Systems (CS)",
    "Usablity (CS)",
    "Educational Technoloogy (CS)",
    "Data Mgt Systems (CS)",
    "Theory (CS)",
    "GT Shenzhen Undergrad Program",
    "Internship Abroad",
    "Global Economics (IP)",
    "Res/CP 51-100 cont/hrs",
    "Res/CP <= 30 cont hrs",
    "Res/CP 31-50 cont hrs",
    "Legislative Requirements",
    "International Relations (IP)",
    "Work-based >= 101 cont hrs",
    "Work-based 51-100 cont hrs",
    "Bioengineering Design II",
    "Mechanical Systems Design II",
    "Thermal Systems Design II"
  ],
  "gradeBases": [
    "ALP ",
    "L ",
    "A ",
    "P ",
    "X ",
    "LP ",
    "AP ",
    "6 ",
    "7 "
  ]
}
```
