### ISSUE TITLE
Lat-Long Location Conversion

### ISSUE THREAD

**Issue by ghost** [GTBitsOfGood/gt-scheduler#14]
## Problem Description
Within the application, each `Section` object contains a field relating to where class is being held (e.g. "Sklies 202"). While this information is certainly helpful to have, there exists the problem of whether we can programmatically plot these locations on the map. If you navigate over to [Google Maps](https://www.google.com/maps/), you'll find that slight nuances in input completely change the output location. For instance, searching "Skiles" takes me to the "Skiles Classroom Building" (correct), whereas searching the _exact_ location, "Skiles 202", yields the "Georgia Institute of Technology" (incorrect).

## Your Goal
- Develop a programmatic way of mapping the provided location strings to their corresponding positions on the map.
    - Read through the [Google Maps API](https://developers.google.com/maps/documentation/javascript/adding-a-google-map) to determine how location markers are added and removed from an existing map.
        - From the looks of it, markers are provided a `position` field containing its `lat` and `lng` coordinates.
- **Note:** A HashMap would be a good solution to this issue, though it may require maintenance in the future if buildings are added/removed from campus. Try thinking of other approaches first—if nothing seems to work out, the HashMap implementation should be more than fine. Let me know what you come up with!

<p align="center"><img width="100%" alt="locations" src="https://user-images.githubusercontent.com/70110771/96053653-e7d99880-0e4d-11eb-90a1-462ecfcb3621.png"></p>

**Comment by JHDeerin** [comment]
@sauravghosal and I got the main functionality working, we just have to add the rest of the locations to the hand-coded lat/long map. It should be in the `lat-long` branch on the crawler.

2 things:
- We might want to do some minor refactoring to keep everything squeaky-clean
- The building lat/longs seem like a perfect candidate to make a new cache array for in the JSON (duplicate information shared by many sections), but we're currently not doing that; we're planning on making a new "locations" cache and going that route unless anyone has objections (@nichabosh )
