### ISSUE TITLE
Create <DaySelection> Component for Map View

### ISSUE THREAD

**Issue by ghost** [GTBitsOfGood/gt-scheduler#19]
### Problem Description
The top-level "Schedule" tab is divided into three subviews: "Courses", "Combinations", and "Calendar". The introduction of the "Map" tab comes with a need for new subviews—in particular, one for day-selection and another for map display. Because the `<MapView>` component is already being covered in issue #11, all that's left to do is integrate and connect the day-selection view to the map. Upon expanding a particular day—only one of which can be open at a time—the expected functionality is to display that day's associated courses and map their locations onto the `<MapView>` component. Reference the image below for a better understanding of what this view will look like.

### Your Goal
* Create a `<DaySelection>` component under `src/components/DaySelection` and add the associated base files.
* Design the component such that it has access to all of the currently-pinned sections' information.
    * As shown in the reference image below, attach and display the associated sections upon expanding a particular day.
* Regarding color, you can either implement a palette similar to Jason's `<Course>` component or simply default to a particular array of colors. Because the colors don't serve any visual purpose in the map—and there will only ever be five options (i.e. MTWRF)—it'd probably be best to just manually assign them some nice-looking pastel colors.

**Note:** Be sure to cover the case in which a day has no sections associated with it. Instead of displaying nothing, be sure to indicate that there's nothing to be seen (similar to classes with no prereqs).

</br><p align="center"><img width="33%" alt="days" src="https://user-images.githubusercontent.com/70110771/97480900-6a705680-192a-11eb-9cfe-07871637268c.png"></p>

**Comment by jazeved0** [comment]
Implemented in https://github.com/GTBitsOfGood/gt-scheduler/pull/26, which was moved to https://github.com/gt-scheduler/website/pull/12
