### ISSUE TITLE
License and copyright notice

### ISSUE THREAD

**Issue by 64json** [GTBitsOfGood/gt-scheduler#27]
Are you all aiming to merge this fork into the original repository, or completely create a diverged version of the website?

If it is the former case, please email me.

If it is the latter case, I would like to request to have a clearly visible license and copyright notice on both the website and README including the following information:

- License (https://github.com/64json/gt-scheduler/blob/master/LICENSE)
- Copyright holder (Jinseo Park, parkjs814@gmail.com)
- Link to the original work
  - From your website to my website.
  - From your README to my README.

Regardless, great work!

**Comment by karpawich** [comment]
@64json Thank you! We'll make sure to update our repo & site accordingly, and soon.

Given our use of the MapBox API, we'll definitely need to maintain a separate fork for the immediate future, but we'll be in touch (I know we've emailed before) about how we can create the best scheduling experience for students moving forward.

Thanks! :)

**Comment by karpawich** [comment]
@64json So that we can officially provide a copyright notice, if you wouldn't mind: 

https://github.com/64json/gt-scheduler/issues/17

**Comment by 64json** [comment]
I just saw you updated the README, and it looks great to me. I appreciate it!

I see it can be quite difficult to put the entire license and copyright notice on the website. How do you think of simply putting something like this as a narrow footer?

Copyright (c) 2020 [Jinseo Park](https://jasonpark.me), [Bits of Good](https://bitsofgood.org), and [the GT Scheduler contributors](https://github.com/GTBitsOfGood/gt-scheduler/graphs/contributors).

**Comment by 64json** [comment]
In the meantime, I'll reach out to you soon via email to discuss about the future plan.

**Comment by 64json** [comment]
@github Any updates on this? It's been two months.
> How do you think of simply putting something like this as a narrow footer?
Copyright (c) 2020 [Jinseo Park](https://jasonpark.me), [Bits of Good](https://bitsofgood.org), and [the GT Scheduler contributors](https://github.com/GTBitsOfGood/gt-scheduler/graphs/contributors).

Also, I just saw https://bitsofgood.org/projects/gt-scheduler. I personally spent an immense amount of time on developing GT Scheduler, and it is very disturbing to see that your website doesn't have any proper attribution to my work. It almost felt as if Bits of Good developed GT Scheduler from scratch until I read the very brief mention within one of the reflection comments.

If your team respects open source culture, please include attribution of any form wherever your project faces the public as soon as possible, regardless of whether we attempt to merge the projects or not.

**Comment by 64json** [comment]
@karpawich Any updates on this? It's been two months.
> How do you think of simply putting something like this as a narrow footer?
Copyright (c) 2020 [Jinseo Park](https://jasonpark.me), [Bits of Good](https://bitsofgood.org), and [the GT Scheduler contributors](https://github.com/GTBitsOfGood/gt-scheduler/graphs/contributors).

Also, I just saw https://bitsofgood.org/projects/gt-scheduler. I personally spent an immense amount of time on developing GT Scheduler, and it is very disturbing to see that your website doesn't have any proper attribution to my work. It almost felt as if Bits of Good developed GT Scheduler from scratch until I read the very brief mention within one of the reflection comments.

If your team respects open source culture, please include attribution of any form wherever your project faces the public as soon as possible, regardless of whether we attempt to merge the projects or not.

**Comment by karpawich** [comment]
@64json I apologize on behalf of Bits of Good! You're absolutely right to be upset at the lack of open source attribution. It looks as though one of our Developers - once when we internally announced our plans to merge - made some changes under the assumption that the attribution was no longer necessary.

I'm sorry personally that I did not resolve this Issue before I stepped away for Winter break. You should receive the attribution that your work deserves, and I will make sure that you get it by the end of today.

~ Max

**Comment by karpawich** [comment]
@64json 

Thank you for notifying me again about the serious lack of attribution. I have gone ahead and attributed you in all of the cited places where you should be mentioned!

Closing this issue, now that attribution has been added to the Bits of Good website, deployed app, and repo.

![Screenshot (140)](https://user-images.githubusercontent.com/34974152/104209934-4805b980-5400-11eb-883f-d7c9a3f5a1f7.png)

![Screenshot (137)](https://user-images.githubusercontent.com/34974152/104205283-36221780-53fc-11eb-8cb6-db644fbcef24.png)

![Screenshot (138)](https://user-images.githubusercontent.com/34974152/104205462-6964a680-53fc-11eb-88fb-cfe91ad1dbc5.png)

![Screenshot (139)](https://user-images.githubusercontent.com/34974152/104205468-6bc70080-53fc-11eb-9645-6afe5d6ca43d.png)

**Comment by karpawich** [comment]
Re-opening in case you have any follow-up requests @64json

**Comment by 64json** [comment]
Looks great to me, and I appreciate the responsiveness.
