### ISSUE TITLE
Schedule download button broken on some browsers

### ISSUE THREAD

**Issue by jazeved0** [GTBitsOfGood/gt-scheduler#28]
On certain browsers (namely, Win10 Firefox), the schedule "Download" button seems to output either invalid or blank images such as:

![image](https://cdn.discordapp.com/attachments/708045188605411369/775187549781622804/schedule-1.png)

### Steps to Reproduce

1. Open up the live scheduler application on Windows 10 Firefox
2. Search for a single class such as "CS 4510"
3. Create a schedule using it
4. Click the "Download" button and view the resultant image

### Notes

**Browser type:**
Firefox 82.0.2 (64-bit)
Windows 10

**Note** that this occurs on both the Bits of Good scheduler and the original repository, so a fix would be relevant to both.

**Comment by Arthelon** [comment]
Noticed this as well

**Comment by jazeved0** [comment]
Potentially related to https://github.com/64json/gt-scheduler/issues/18 on the upstream repository

**Comment by jazeved0** [comment]
Fixed with #36
