### ISSUE TITLE
Seat capacities fails to load ("N/A")

### ISSUE THREAD

**Issue by AlexanderPuckhaber** [GTBitsOfGood/gt-scheduler#33]
To replicate:

- Mouse over chair icon. Always shows "N/A" for me

What seems to be the issue: CORS proxy used in Section.js https://github.com/GTBitsOfGood/gt-scheduler/blob/384376de209be885bfbc22b0541933fc5bf63ce7/src/beans/Section.js#L72

Looking at the Network debugger, the request to the CORS proxy returns 200 (success), but the data the proxy returns from the target URL is a 403 forbidden error. 

You can also see this by opening a demo of the CORS proxy (like here: https://robwu.nl/cors-anywhere.html) and put in an example oscar url (like this one: https://oscar.gatech.edu/pls/bprod/bwckschd.p_disp_detail_sched?term_in=202102&crn_in=24968). What returns seems to be an HTML response from some kind of Oracle database server, which I suspect is what is hosting OSCAR. It says: 

> "The request cannot be processed because this resource does not support Cross Origin Sharing requests, or the request Origin is not authorized to access this resource. If ords is being reverse proxied ensure the front end server is propagating the host name, for mod_proxy ensure ProxyPreserveHost is set to On"

Idk how to fix this... it might be possible that OSCAR's database server is no longer playing nice with this particular CORS proxy. Maybe the headers need to be changed? Or maybe the settings in this cors-anywhere demo no longer create the right kind of request for OSCAR (I know it *used* to work, and of course I can access the OSCAR pages just fine...)

If this CORS-proxy method can't be fixed, you could add a function to the periodic OSCAR scraper to also hit the individual CRNs to get the course capacities for each section. (It looks like Courseoff does something like this, I definitely remember it used to load class capacities one by one like it was rate-limited, now it gets it from a Courseoff server at-once). It takes approx 2 hours to hit every crn, so you might want to run the web-scraper for this nightly, but just add a disclaimer that the info may be out-of-date and to check yourself before trying to register, and it should be ok

**Comment by jazeved0** [comment]
This is related to needing a backend to remove the need for the CORS proxy mitigation (that no longer works).

Related to https://github.com/64json/gt-scheduler/issues/14 on the upstream repository in terms of the needed fix being a backend server.

**Comment by jazeved0** [comment]
Fixed/tracked in https://github.com/gt-scheduler/backend/issues/1 by using a simple CORS proxy for now. If we end up running into rate-limiting or other issues, we may have to look into other solutions.
